### PR TITLE
Fix missing coordinates from points download

### LINKED ISSUE #363: Points download excludes coordinates
Staging area (0.13 cont)

https://trello.com/c/0B7HB3xM/761-points-download-excludes-coordinates

### PR DESCRIPTION
**Pull request by michaelglenister**
## Description

Point downloads were missing coordinates

## Related Issue
Closes  #363

## How to test it locally
Check if point download xlsx contains coordinate data

## Checklist

- [x]  🚀 is the code ready to be merged and go live?
- [x]  🛠 does it work (build) locally
- [x] 👩‍🎨 does the design matches the [Demo](https://wazimap-ng-v1.webflow.io/demo)

### Pull Request

- [x]  📰 good title
- [x]  📝good description
- [x]  🔖 issue linked
- [ ]  📖 changelog filled out
- [x] commit messages are meaningful

### Code Quality

- [x]  🚧 no commented out code
- [x]  🖨 no unnecessary logging
- [x]  🎱 no magic numbers

### Testing

- [ ]  ✅ added (appropriate) unit tests
- [ ]  💢 edge cases in tests were considered
- [ ]  ✅ ran tests locally & are passing

### CODE REVIEW

File: src/js/utils.js [hunk 1]
```diff
@@ -356,9 +356,10 @@ export function extractSheetsData(data) {
 export function extractSheetData(rawData, categoryName) {
     const sheetName = getSheetName(categoryName);
     let rows = rawData.features.map((f) => {
-        let {properties: {name, data}} = f;
+        let {geometry: {coordinates:[longitude, latitude]}, properties: {name, data}} = f;
```
Comment (milafrerichs) [inline src/js/utils.js:359]: 🔥

**Review by milafrerichs — APPROVED** [review]
